repository:
  default_branch: main

labels:
  - name: ":bug:"
    color: ffffff
    description: A bug!

  - name: ":shipit:"
    color: ffffff
    description: Ship it

  - name: ":x:"
    color: ffffff
    description: Nope!
